import 'reflect-metadata';
import './container';
import express, { type Request, type Response, type NextFunction } from 'express';
import cors from 'cors';
import swaggerUi from 'swagger-ui-express';
import { readFileSync } from 'fs';
import { join } from 'path';
import pino from 'pino';
import { env } from './config/env.config';
import { isAppError, InternalError } from './utils/errors';
import type { ErrorResponseBody } from './utils/errors';

const logger = pino({ name: 'server' });

// TSOA-generated routes — regenerated by `pnpm tsoa:spec-and-routes`
// Imported via RegisterRoutes export from the generated file.
import { RegisterRoutes } from './generated/routes';

const app: express.Express = express();

// ── Middleware ──────────────────────────────────────────────────────────────
app.use(
  cors({
    origin: env.CORS_ORIGIN,
    credentials: true,
  })
);
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// ── Swagger UI ──────────────────────────────────────────────────────────────
if (env.ENABLE_SWAGGER) {
  const swaggerDocument = JSON.parse(
    readFileSync(join(__dirname, 'generated/swagger.json'), 'utf-8')
  ) as Record<string, unknown>;
  app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));
  logger.info(`Swagger UI available at http://${env.HOST}:${env.PORT}/api-docs`);
}

// ── TSOA Routes ─────────────────────────────────────────────────────────────
RegisterRoutes(app);

// ── Health check ────────────────────────────────────────────────────────────
app.get('/health', (_req: Request, res: Response) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

// ── Global error handler ─────────────────────────────────────────────────────
// Per coding rules §4.2: error middleware is the ONLY place that calls res.status().
app.use((err: unknown, _req: Request, res: Response, _next: NextFunction): void => {
  if (isAppError(err)) {
    const body = err.toResponseBody();
    res.status(err.statusCode).json(body);
    return;
  }

  // tsoa validation errors come as ValidateError with a { fields } property
  if (
    err !== null &&
    typeof err === 'object' &&
    'status' in err &&
    (err as { status: unknown }).status === 400
  ) {
    const fields = 'fields' in err ? (err as { fields: unknown }).fields : undefined;
    const body: ErrorResponseBody = {
      error: 'ValidationError',
      message: 'Validation failed',
      details: fields !== undefined ? { fields } : {},
    };
    res.status(400).json(body);
    return;
  }

  const internal = new InternalError('An unexpected error occurred');
  const message = err instanceof Error ? err.message : String(err);
  logger.error({ error: message }, 'Unhandled server error');
  res.status(500).json(internal.toResponseBody());
});

// ── Start ────────────────────────────────────────────────────────────────────
const server = app.listen(env.PORT, env.HOST, () => {
  logger.info(`BFF server running on http://${env.HOST}:${env.PORT}`);
  logger.info(`Environment: ${env.NODE_ENV}`);
});

// ── Graceful shutdown ────────────────────────────────────────────────────────
const shutdown = (): void => {
  logger.info('Shutting down gracefully...');
  server.close(() => {
    logger.info('Server closed.');
    process.exit(0);
  });
};

process.on('SIGTERM', shutdown);
process.on('SIGINT', shutdown);

export default app;
