import 'reflect-metadata';
import './container';
import express from 'express';
import cors from 'cors';
import swaggerUi from 'swagger-ui-express';
import { readFileSync } from 'fs';
import { join } from 'path';
import { env } from './config/env.config';

// TSOA-generated routes — regenerated by `pnpm tsoa:spec-and-routes`
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { RegisterRoutes } = require('./generated/routes') as {
  RegisterRoutes: (app: express.Express) => void;
};

const app: express.Express = express();

// ── Middleware ──────────────────────────────────────────────────────────────
app.use(
  cors({
    origin: env.CORS_ORIGIN,
    credentials: true,
  })
);
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// ── Swagger UI ──────────────────────────────────────────────────────────────
if (env.ENABLE_SWAGGER) {
  const swaggerDocument = JSON.parse(
    readFileSync(join(__dirname, 'generated/swagger.json'), 'utf-8')
  ) as Record<string, unknown>;
  app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));
  console.log(`📖 Swagger UI available at http://${env.HOST}:${env.PORT}/api-docs`);
}

// ── TSOA Routes ─────────────────────────────────────────────────────────────
RegisterRoutes(app);

// ── Health check ────────────────────────────────────────────────────────────
app.get('/health', (_req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

// ── Start ────────────────────────────────────────────────────────────────────
const server = app.listen(env.PORT, env.HOST, () => {
  console.log(`🚀 BFF server running on http://${env.HOST}:${env.PORT}`);
  console.log(`   Environment: ${env.NODE_ENV}`);
});

// ── Graceful shutdown ────────────────────────────────────────────────────────
const shutdown = (): void => {
  console.log('Shutting down gracefully...');
  server.close(() => {
    console.log('Server closed.');
    process.exit(0);
  });
};

process.on('SIGTERM', shutdown);
process.on('SIGINT', shutdown);

export default app;
